### PR TITLE
increase the runtime for fft

### PR DESCRIPTION
**Pull request by deyaaeldeen**
Although the input we use is the default used in Gambit Scheme benchmarks, it causes very low runtime, ~ 0.12 seconds. This new input will put the worst runtime above the 3 seconds mark while the mean is 1.44s and the best is 0.11s with configuration index 17. This might add an extra day to the total experiment runtime.
[fft17.log](https://github.com/Gradual-Typing/benchmarks/files/2435607/fft17.log)

### CODE REVIEW

**Comment by akuhlens** [comment]
We might try stepping it up slightly slower, adding a full day to benchmarking is quite and expense. I see you have increased the input by a factor of 16. Does input size have a linear increase in time? If so maybe we should start with 1/2 or 1/4 of that time. To do this scientifically we need to calculate confidence intervals.

**Comment by deyaaeldeen** [comment]
I want the mean to be around 1 second, less input will put the mean less than a second.

**Comment by akuhlens** [comment]
Why do you want the mean to be 1 second?

**Comment by deyaaeldeen** [comment]
We can discuss this offline. I am available on Slack.

**Pull request merged**
